PORTFOLIO_STOCKS = {
  "AETHER": {"yf": "AETHER.NS", "isin": "INE0BWX01014", "name": "Aether Industries", "sector": "Chemicals", "mcap": "MID"},
  "APOLLO": {"yf": "APOLLOMICRO.NS", "isin": "INE713T01028", "name": "Apollo Micro Systems", "sector": "Defence", "mcap": "SMALL"},
  "ARKADE": {"yf": "ARKADE.NS", "isin": "INE0QRL01017", "name": "Arkade Developers", "sector": "Real Estate", "mcap": "SMALL"},
  "ASHOKLEY": {"yf": "ASHOKLEY.NS", "isin": "INE208A01029", "name": "Ashok Leylnd", "sector": "Auto", "mcap": "LARGE"},
  "BAJAJHFL": {"yf": "BAJAJHFL.NS", "isin": "INE377Y01014", "name": "Bajaj Housing Finance", "sector": "Finance", "mcap": "LARGE"},
  "BCLIND": {"yf": "BCLIND.NS", "isin": "INE412G01024", "name": "Bhatinda Ch.(Bse Indonext)", "sector": "Unknown", "mcap": "UNKNOWN"},
  "BHEL": {"yf": "BHEL.NS", "isin": "INE257A01026", "name": "Bhel", "sector": "Capital Goods", "mcap": "LARGE"},
  "BPCL": {"yf": "BPCL.NS", "isin": "INE029A01011", "name": "Bharat Petroleum Corporation L", "sector": "Oil & Gas", "mcap": "LARGE"},
  "CARERATING": {"yf": "CARERATING.NS", "isin": "INE752H01013", "name": "Care Rating", "sector": "Finance", "mcap": "SMALL"},
  "CCL": {"yf": "CCL.NS", "isin": "INE421D01022", "name": "Ccl Produts", "sector": "Unknown", "mcap": "UNKNOWN"},
  "CDSL": {"yf": "CDSL.NS", "isin": "INE736A01011", "name": "Central Depo Ser (I)", "sector": "Unknown", "mcap": "UNKNOWN"},
  "COALINDIA": {"yf": "COALINDIA.NS", "isin": "INE522F01014", "name": "Coal India", "sector": "Unknown", "mcap": "UNKNOWN"},
  "COCHINSHIP": {"yf": "COCHINSHIP.NS", "isin": "INE704P01025", "name": "Cochin Shipyard", "sector": "Shipping", "mcap": "MID"},
  "COFORGE": {"yf": "COFORGE.NS", "isin": "INE591G01025", "name": "Coforge", "sector": "IT", "mcap": "LARGE"},
  "DATAMATICS": {"yf": "DATAMATICS.NS", "isin": "INE365B01017", "name": "Datam Glob", "sector": "IT", "mcap": "SMALL"},
  "DRREDDY": {"yf": "DRREDDY.NS", "isin": "INE089A01031", "name": "Dr.Reddy~S Laboratories", "sector": "Pharma", "mcap": "LARGE"},
  "ETERNAL": {"yf": "ETERNAL.NS", "isin": "INE758T01015", "name": "Eternal", "sector": "Consumer", "mcap": "LARGE"},
  "FIRSTCRY": {"yf": "FIRSTCRY.NS", "isin": "INE02RE01045", "name": "Brainbees Solutions", "sector": "Retail", "mcap": "LARGE"},
  "FSL": {"yf": "FSL.NS", "isin": "INE684F01012", "name": "Fsl", "sector": "IT", "mcap": "MID"},
  "GAIL": {"yf": "GAIL.NS", "isin": "INE129A01019", "name": "Gail India", "sector": "Oil & Gas", "mcap": "LARGE"},
  "GENSOL": {"yf": "GENSOL.NS", "isin": "INE06H201014", "name": "Gensol Engineering", "sector": "Renewable", "mcap": "SMALL"},
  "GLAND": {"yf": "GLAND.NS", "isin": "INE068V01023", "name": "Gland", "sector": "Pharma", "mcap": "MID"},
  "GOLDBEES": {"yf": "GOLDBEES.NS", "isin": "INF204KB17I5", "name": "Goldbees", "sector": "Unknown", "mcap": "UNKNOWN"},
  "GREAVESCOT": {"yf": "GREAVESCOT.NS", "isin": "INE224A01026", "name": "Greaves Cott", "sector": "Auto", "mcap": "SMALL"},
  "HDFCGOLD": {"yf": "HDFCGOLD.NS", "isin": "INF179KC1981", "name": "Hdfcmfgetf", "sector": "Unknown", "mcap": "UNKNOWN"},
  "HINDOILEXP": {"yf": "HINDOILEXP.NS", "isin": "INE345A01011", "name": "Hind.Oil Exp", "sector": "Oil & Gas", "mcap": "SMALL"},
  "HINDPETRO": {"yf": "HINDPETRO.NS", "isin": "INE094A01015", "name": "Hindustan Petroleum Corp.", "sector": "Oil & Gas", "mcap": "LARGE"},
  "IEX": {"yf": "IEX.NS", "isin": "INE022Q01020", "name": "Indian Energy Exchange", "sector": "Energy", "mcap": "MID"},
  "IFCI": {"yf": "IFCI.NS", "isin": "INE039A01010", "name": "Ifci", "sector": "Finance", "mcap": "SMALL"},
  "IREDA": {"yf": "IREDA.NS", "isin": "INE202E01016", "name": "Indian Renewable Energy Develo", "sector": "Renewable", "mcap": "LARGE"},
  "IRFC": {"yf": "IRFC.NS", "isin": "INE053F01010", "name": "Indian Railway Finance", "sector": "Finance", "mcap": "LARGE"},
  "JSL": {"yf": "JSL.NS", "isin": "INE220G01021", "name": "Jsl", "sector": "Unknown", "mcap": "UNKNOWN"},
  "LATENTVIEW": {"yf": "LATENTVIEW.NS", "isin": "INE0I7C01011", "name": "Latent View Analytics", "sector": "IT", "mcap": "MID"},
  "NEWGEN": {"yf": "NEWGEN.NS", "isin": "INE619B01017", "name": "Newgen", "sector": "IT", "mcap": "MID"},
  "NIFTYBEES": {"yf": "NIFTYBEES.NS", "isin": "INF204KB14I2", "name": "Nifty Bees", "sector": "Unknown", "mcap": "UNKNOWN"},
  "NITINSPIN": {"yf": "NITINSPIN.NS", "isin": "INE229H01012", "name": "Nitinspinner", "sector": "Textiles", "mcap": "SMALL"},
  "NTPC": {"yf": "NTPC.NS", "isin": "INE733E01010", "name": "Ntpc", "sector": "Energy", "mcap": "LARGE"},
  "NTPCGREEN": {"yf": "NTPCGREEN.NS", "isin": "INE0ONG01011", "name": "Ntpc Green Energy", "sector": "Renewable", "mcap": "LARGE"},
  "NYKAA": {"yf": "NYKAA.NS", "isin": "INE388Y01029", "name": "Fsn E-Commerce Ventures Limite", "sector": "Retail", "mcap": "LARGE"},
  "OLAELEC": {"yf": "OLAELEC.NS", "isin": "INE0LXG01040", "name": "Ola Electric Mobility", "sector": "Auto", "mcap": "LARGE"},
  "OLECTRA": {"yf": "OLECTRA.NS", "isin": "INE260D01016", "name": "Olectra Greentech", "sector": "Auto", "mcap": "MID"},
  "ONGC": {"yf": "ONGC.NS", "isin": "INE213A01029", "name": "Ong Corp", "sector": "Oil & Gas", "mcap": "LARGE"},
  "PAYTM": {"yf": "PAYTM.NS", "isin": "INE982J01020", "name": "One97 Communications", "sector": "Fintech", "mcap": "LARGE"},
  "PCBL": {"yf": "PCBL.NS", "isin": "INE602A01031", "name": "Phil Car Blk", "sector": "Chemicals", "mcap": "MID"},
  "POLICYBZR": {"yf": "POLICYBZR.NS", "isin": "INE417T01026", "name": "Pb Fintech", "sector": "Fintech", "mcap": "LARGE"},
  "SAIL": {"yf": "SAIL.NS", "isin": "INE114A01011", "name": "Steel Author", "sector": "Metals", "mcap": "LARGE"},
  "SALASAR": {"yf": "SALASAR.NS", "isin": "INE170V01027", "name": "Salasar Techno Engg.", "sector": "Unknown", "mcap": "UNKNOWN"},
  "SCI": {"yf": "SCI.NS", "isin": "INE109A01011", "name": "Shipping Cor", "sector": "Shipping", "mcap": "MID"},
  "SHRIRAMFIN": {"yf": "SHRIRAMFIN.NS", "isin": "INE721A01047", "name": "Shriram Transport", "sector": "Unknown", "mcap": "UNKNOWN"},
  "SHYAMMETL": {"yf": "SHYAMMETL.NS", "isin": "INE810G01011", "name": "Shyam Metalics And Energy", "sector": "Metals", "mcap": "MID"},
  "SILVERBEES": {"yf": "SILVERBEES.NS", "isin": "INF204KC1402", "name": "Nipponamc - Netfsilver", "sector": "Unknown", "mcap": "UNKNOWN"},
  "SOBHA": {"yf": "SOBHA.NS", "isin": "INE671H01015", "name": "Sobha Dev", "sector": "Real Estate", "mcap": "MID"},
  "TATASTEEL": {"yf": "TATASTEEL.NS", "isin": "INE081A01020", "name": "Tata Stl", "sector": "Metals", "mcap": "LARGE"},
  "TATSILV": {"yf": "TATSILV.NS", "isin": "INF277KA1984", "name": "Tataaml-Tatsilv", "sector": "Unknown", "mcap": "UNKNOWN"},
  "TATVA": {"yf": "TATVA.NS", "isin": "INE0GK401011", "name": "Tatva Chintan Pharma Chem Limi", "sector": "Unknown", "mcap": "UNKNOWN"},
  "TI": {"yf": "TI.NS", "isin": "INE133E01013", "name": "Tilaknag Ind(Bse Indonext)", "sector": "Unknown", "mcap": "UNKNOWN"},
  "TMCV": {"yf": "TMCV.NS", "isin": "INE1TAE01010", "name": "Tata Motors", "sector": "Unknown", "mcap": "UNKNOWN"},
  "TMPV": {"yf": "TMPV.NS", "isin": "INE155A01022", "name": "Tata Motors", "sector": "Unknown", "mcap": "UNKNOWN"},
  "UJJIVANSFB": {"yf": "UJJIVANSFB.NS", "isin": "INE551W01018", "name": "Ujjivansmallfinancbank", "sector": "Unknown", "mcap": "UNKNOWN"},
  "VEDL": {"yf": "VEDL.NS", "isin": "INE205A01025", "name": "Vedanta", "sector": "Unknown", "mcap": "UNKNOWN"},
  "WELSPUNLIV": {"yf": "WELSPUNLIV.NS", "isin": "INE192B01031", "name": "Welspun Indi", "sector": "Unknown", "mcap": "UNKNOWN"},
}
