PORTFOLIO_STOCKS = {
  "AETHER":         {"yf": "AETHER.NS",        "isin": "INE0BWX01014", "name": "Aether Industries",         "sector": "Chemicals",       "mcap": "MID"},
  "APOLLOMICRO":    {"yf": "APOLLOMICRO.NS",   "isin": "INE713T01028", "name": "Apollo Micro Systems",      "sector": "Defence",         "mcap": "SMALL"},
  "ARKADE":         {"yf": "ARKADE.NS",        "isin": "INE0QRL01017", "name": "Arkade Developers",         "sector": "Real Estate",     "mcap": "SMALL"},
  "ASHOKLEY":       {"yf": "ASHOKLEY.NS",      "isin": "INE208A01029", "name": "Ashok Leyland",             "sector": "Auto",            "mcap": "LARGE"},
  "BAJAJHFL":       {"yf": "BAJAJHFL.NS",      "isin": "INE377Y01014", "name": "Bajaj Housing Finance",     "sector": "Finance",         "mcap": "LARGE"},
  "BCL":            {"yf": "BCL.NS",           "isin": "INE412G01024", "name": "BCL Industries",            "sector": "Agro",            "mcap": "SMALL"},
  "BHEL":           {"yf": "BHEL.NS",          "isin": "INE257A01026", "name": "Bharat Heavy Electricals",  "sector": "Capital Goods",   "mcap": "LARGE"},
  "BPCL":           {"yf": "BPCL.NS",          "isin": "INE029A01011", "name": "BPCL",                      "sector": "Oil & Gas",       "mcap": "LARGE"},
  "FIRSTCRY":       {"yf": "FIRSTCRY.NS",      "isin": "INE02RE01045", "name": "Brainbees Solutions",       "sector": "Retail",          "mcap": "LARGE"},
  "CARERATING":     {"yf": "CARERATING.NS",    "isin": "INE752H01013", "name": "CARE Ratings",              "sector": "Finance",         "mcap": "SMALL"},
  "CCLPROD":        {"yf": "CCLPROD.NS",       "isin": "INE421D01022", "name": "CCL Products",              "sector": "FMCG",            "mcap": "SMALL"},
  "COCHINSHIP":     {"yf": "COCHINSHIP.NS",    "isin": "INE704P01025", "name": "Cochin Shipyard",           "sector": "Shipping",        "mcap": "MID"},
  "COFORGE":        {"yf": "COFORGE.NS",       "isin": "INE591G01017", "name": "Coforge Limited",           "sector": "IT",              "mcap": "LARGE"},
  "DATAMATICS":     {"yf": "DATAMATICS.NS",    "isin": "INE365B01017", "name": "Datamatics Global",         "sector": "IT",              "mcap": "SMALL"},
  "DRREDDY":        {"yf": "DRREDDY.NS",       "isin": "INE089A01031", "name": "Dr Reddys Laboratories",    "sector": "Pharma",          "mcap": "LARGE"},
  "ETERNAL":        {"yf": "ETERNAL.NS",       "isin": "INE758T01015", "name": "Eternal Limited",           "sector": "Consumer",        "mcap": "LARGE"},
  "FSL":            {"yf": "FSL.NS",           "isin": "INE684F01012", "name": "Firstsource Solutions",     "sector": "IT",              "mcap": "MID"},
  "NYKAA":          {"yf": "NYKAA.NS",         "isin": "INE388Y01029", "name": "FSN E-Commerce (Nykaa)",    "sector": "Retail",          "mcap": "LARGE"},
  "GAIL":           {"yf": "GAIL.NS",          "isin": "INE129A01019", "name": "GAIL India",                "sector": "Oil & Gas",       "mcap": "LARGE"},
  "GENSOL":         {"yf": "GENSOL.NS",        "isin": "INE06H201014", "name": "Gensol Engineering",        "sector": "Renewable",       "mcap": "SMALL"},
  "GLAND":          {"yf": "GLAND.NS",         "isin": "INE068V01023", "name": "Gland Pharma",              "sector": "Pharma",          "mcap": "MID"},
  "GREAVESCOT":     {"yf": "GREAVESCOT.NS",    "isin": "INE224A01026", "name": "Greaves Cotton",            "sector": "Auto",            "mcap": "SMALL"},
  "HINDOILEXP":     {"yf": "HINDOILEXP.NS",    "isin": "INE345A01011", "name": "Hindustan Oil Exploration", "sector": "Oil & Gas",       "mcap": "SMALL"},
  "HINDPETRO":      {"yf": "HINDPETRO.NS",     "isin": "INE094A01015", "name": "HPCL",                      "sector": "Oil & Gas",       "mcap": "LARGE"},
  "IFCI":           {"yf": "IFCI.NS",          "isin": "INE039A01010", "name": "IFCI Limited",              "sector": "Finance",         "mcap": "SMALL"},
  "IEX":            {"yf": "IEX.NS",           "isin": "INE022Q01020", "name": "Indian Energy Exchange",    "sector": "Energy",          "mcap": "MID"},
  "IRFC":           {"yf": "IRFC.NS",          "isin": "INE053F01010", "name": "Indian Railway Finance",    "sector": "Finance",         "mcap": "LARGE"},
  "IREDA":          {"yf": "IREDA.NS",         "isin": "INE202E01016", "name": "Indian Renewable Energy",   "sector": "Renewable",       "mcap": "LARGE"},
  "JINDALSTEL":     {"yf": "JINDALSTEL.NS",    "isin": "INE749A01030", "name": "Jindal Steel & Power",      "sector": "Metals",          "mcap": "LARGE"},
  "LATENTVIEW":     {"yf": "LATENTVIEW.NS",    "isin": "INE0IN801015", "name": "Latent View Analytics",     "sector": "IT",              "mcap": "MID"},
  "NEWGEN":         {"yf": "NEWGEN.NS",        "isin": "INE619B01017", "name": "Newgen Software",           "sector": "IT",              "mcap": "MID"},
  "NITINSPIN":      {"yf": "NITINSPIN.NS",     "isin": "INE858B01029", "name": "Nitin Spinners",            "sector": "Textiles",        "mcap": "SMALL"},
  "NTPCGREEN":      {"yf": "NTPCGREEN.NS",     "isin": "INE0QPH01011", "name": "NTPC Green Energy",         "sector": "Renewable",       "mcap": "LARGE"},
  "NTPC":           {"yf": "NTPC.NS",          "isin": "INE733E01010", "name": "NTPC Limited",              "sector": "Energy",          "mcap": "LARGE"},
  "OLAELEC":        {"yf": "OLAELEC.NS",       "isin": "INE0LUB01010", "name": "Ola Electric",              "sector": "Auto",            "mcap": "LARGE"},
  "OLECTRA":        {"yf": "OLECTRA.NS",       "isin": "INE260D01016", "name": "Olectra Greentech",         "sector": "Auto",            "mcap": "MID"},
  "PAYTM":          {"yf": "PAYTM.NS",         "isin": "INE982J01020", "name": "Paytm (One97 Comm)",        "sector": "Fintech",         "mcap": "LARGE"},
  "ONGC":           {"yf": "ONGC.NS",          "isin": "INE213A01029", "name": "ONGC",                      "sector": "Oil & Gas",       "mcap": "LARGE"},
  "POLICYBZR":      {"yf": "POLICYBZR.NS",     "isin": "INE417T01026", "name": "PB Fintech (PolicyBazaar)", "sector": "Fintech",         "mcap": "LARGE"},
  "PCBL":           {"yf": "PCBL.NS",          "isin": "INE196H01026", "name": "PCBL Chemical",             "sector": "Chemicals",       "mcap": "MID"},
  "SAIL":           {"yf": "SAIL.NS",          "isin": "INE114A01011", "name": "SAIL",                      "sector": "Metals",          "mcap": "LARGE"},
  "SALASARTECHNO":  {"yf": "SALASARTECHNO.NS", "isin": "INE229V01012", "name": "Salasar Techno Engineering","sector": "Capital Goods",   "mcap": "SMALL"},
  "SCI":            {"yf": "SCI.NS",           "isin": "INE109A01011", "name": "Shipping Corporation",      "sector": "Shipping",        "mcap": "MID"},
  "SHYAMMETL":      {"yf": "SHYAMMETL.NS",     "isin": "INE594I01017", "name": "Shyam Metalics",            "sector": "Metals",          "mcap": "MID"},
  "SOBHA":          {"yf": "SOBHA.NS",         "isin": "INE671H01015", "name": "Sobha Limited",             "sector": "Real Estate",     "mcap": "MID"},
  "TATAMOTORS":     {"yf": "TATAMOTORS.NS",    "isin": "INE155A01022", "name": "Tata Motors",               "sector": "Auto",            "mcap": "LARGE"},
  "TATASTEEL":      {"yf": "TATASTEEL.NS",     "isin": "INE081A01012", "name": "Tata Steel",                "sector": "Metals",          "mcap": "LARGE"},
  "TATVACHINTAN":   {"yf": "TATVACHINTAN.NS",  "isin": "INE337R01012", "name": "Tatva Chintan Pharma",      "sector": "Chemicals",       "mcap": "SMALL"},
  "TILAKNAGAR":     {"yf": "TILAKNAGAR.NS",    "isin": "INE133A01014", "name": "Tilaknagar Industries",     "sector": "FMCG",            "mcap": "SMALL"},
  "UJJIVAN":        {"yf": "UJJIVAN.NS",       "isin": "INE046P01024", "name": "Ujjivan Small Finance",     "sector": "Finance",         "mcap": "MID"},
  "VEDANTA":        {"yf": "VEDANTA.NS",       "isin": "INE205A01025", "name": "Vedanta Limited",           "sector": "Metals",          "mcap": "LARGE"},
  "WELSPUN":        {"yf": "WELSPUN.NS",       "isin": "INE192B01031", "name": "Welspun Living",            "sector": "Textiles",        "mcap": "MID"},
}
